datasets:
  - key: ap19-olr
    labels:
    - bo-CN
    - id
    - ja
    - kk-CN
    - ko
    - ru
    - ug-CN
    - vi
    - yue-CN
    - zh-CN
    splits:
      - key: train
        path: /m/triton/scratch/elec/puhe/p/lindgrm1/exp/data/ap19-olr/train_no_region
        datafiles:
            - utt2path
            - utt2label
      - key: dev
        path: /m/triton/scratch/elec/puhe/p/lindgrm1/exp/data/ap19-olr/dev_no_region
        datafiles:
            - utt2path
            - utt2label
      - key: test
        path: /m/triton/scratch/elec/puhe/p/lindgrm1/exp/data/ap19-olr/test_no_region
        datafiles:
            - utt2path
            - utt2label
  - key: mgb3
    labels:
    - afb
    - ar-x-lav
    - ar-x-nor
    - arb
    - arz
    splits:
      - key: train
        path: /m/triton/scratch/elec/puhe/p/lindgrm1/exp/data/mgb3/train_5dev0.9_augment
        datafiles:
            - utt2path
            - utt2label
      - key: dev
        path: /m/triton/scratch/elec/puhe/p/lindgrm1/exp/data/mgb3/dev0.1_fixed_labels
        datafiles:
            - utt2path
            - utt2label
      - key: test
        path: /m/triton/scratch/elec/puhe/p/lindgrm1/exp/data/mgb3/test_fixed_labels
        datafiles:
            - utt2path
            - utt2label
  - key: dosl
    labels:
    - be
    - bg
    - cs
    - hr
    - mk
    - pl
    - ru
    - sk
    - sl
    - sr
    - uk
    splits:
      - key: train
        path: /m/triton/scratch/elec/puhe/p/lindgrm1/exp/data/dosl/train
        datafiles:
            - utt2path
            - utt2label
      - key: dev
        path: /m/triton/scratch/elec/puhe/p/lindgrm1/exp/data/dosl/dev
        datafiles:
            - utt2path
            - utt2label
      - key: test
        path: /m/triton/scratch/elec/puhe/p/lindgrm1/exp/data/dosl/test
        datafiles:
            - utt2path
            - utt2label

pre_initialize:
  shuffle_utterances: true
  allow_unknown_labels: false

post_initialize:
  check_wav_headers: true
  num_prefetched_signals: 5000

pre_process:
  filters:
    equal:
      key: sample_rate
      value: 16000
  repeat_too_short_signals:
    min_length_ms: 2000
  rms_vad:
    strength: 0.1
    vad_frame_length_ms: 10
    min_non_speech_length_ms: 100
  chunks:
    length_ms: 2000
    step_ms: 1500
  cache:
    directory: /m/triton/scratch/elec/puhe/p/lindgrm1/exp/models/combined3/cache
    batch_size: 1000
    key: signals_rmsvad_chunks_2sec
    log_interval: 20000
    consume: false

features:
  batch_size: 1024
  type: logmelspectrogram
  spectrogram:
    frame_length_ms: 25
    frame_step_ms: 10
    fft_length: 512
  melspectrogram:
    num_mel_bins: 40
    fmin: 20.0
    fmax: 8000.0
  window_normalization:
    normalize_variance: false

post_process:
  remap_keys:
    dataset: null
    feature_type: null
    label: null
    path: null
    sample_rate: null
    signal: null
  cache:
    directory: /tmp/tensorflow-cache/xvec-2d-combined3
    batch_size: 1000
    key: logmelspectrogram
    consume: false

experiment:
  cache_directory: /m/triton/scratch/elec/puhe/p/lindgrm1/exp/models/combined3/cache
  name: xvec-2d-combined3
  model:
    key: xvector_2d
  optimizer:
    cls: Adam
    kwargs:
      learning_rate: 0.0001
  input_shape: [198, 40]
  output_shape: [25]
  callbacks:
    - cls: TensorBoard
    - cls: ModelCheckpoint
      format: "epoch{epoch:06d}__val_loss{val_loss:.12f}__val_sparse_categorical_accuracy{val_sparse_categorical_accuracy:.12f}.hdf5"
      kwargs:
        monitor: val_loss
        mode: min
    - cls: EarlyStopping
      kwargs:
        monitor: val_loss
        patience: 20
        mode: min
    - cls: LearningRateDateLogger
  metrics:
    - cls: SparseCategoricalAccuracy
  loss:
    cls: SparseCategoricalCrossentropy
    kwargs:
      from_logits: true
  keras_fit_kwargs:
    epochs: 200
  data:
    train:
      split: train
      shuffle_buffer_size: 20000
      batch_size: 64
    validation:
      split: dev
      batch_size: 64
    test:
      split: test
      batch_size: 64
      evaluate_metrics:
        - name: sparse_average_detection_cost
        - name: sklearn_classification_report
        - name: average_f1_score
        - name: confusion_matrix
